
name: Status trigger


on:
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: dnswarden/status
          event-type: uptime
